version: "3.9"
services:
  arangodb:
    restart: always
    container_name: "lua-arangodb-dev"
    image: "arangodb/arangodb:latest"
    ports:
      - "8529:8529"
    environment:
      - ARANGO_ROOT_PASSWORD=openSesame
